site_name: database-template-preview
docs_dir: ./preview/

nav:
- Home: index.md
- generated/gtdb220.md
- generated/gtdb226.md
- generated/ncbi_euks_2025_01.md
- generated/ncbi_viruses_2025_01.md

markdown_extensions:
  - toc:
      permalink: true
  - def_list
  - attr_list
  - admonition

plugins:
  - search

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    