#! /usr/bin/env python
# this script automatically generated by code in https://github.com/sourmash-bio/2025-sourmash-databases-doc-template/
# template file: templates/check-urls.py

import requests
import sys

urls = [
{% for coll in collections -%}
{% for db in coll.sketches -%}
{% for dbfile in db.files -%}
    '{{ dbfile.download_url }}',
{% endfor -%}
{% endfor -%}
{% for tax in coll.taxonomies -%}
    '{{ tax.download_url }}',
{% endfor -%}
{% endfor -%}
]

def main():
    n_failed = 0
    for url in urls:
        x = requests.head(url)

        if x.status_code != 200:
            print('ERROR: the following URL does not exist.')
            print(url)
            n_failed += 1

    if n_failed > 0:
        print(f'{n_failed} of {len(urls)} URLs failed. See errors above.')
        return -1
    else:
        print(f'{len(urls)} URLs succeeded. Nice work!!')
        return 0


if __name__ == '__main__':
    sys.exit(main())
